name: go custom action

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Package and and upload
        uses: ./ # Uses an action in the root directory
        id: package
        with:
          name: my-test-name
      - name: Get the output
        run: echo "The output was ${{ steps.package.outputs.greeting }}"

